version: '3.8'
services:
 ipsec:
    image: docker.io/viapip/ipsec-vpn:alpha-0.15
    container_name: ipsec-vpn
    env_file:
      - ./.env
    restart: always
    volumes:
      - ./data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true